# Generated by Django 3.1.2 on 2021-01-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20210110_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='type_user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='type_user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type_user',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.CharField(choices=[('Period 1', '8:00-10:00'), ('Period 2', '10:00-12:00'), ('Period 3', '12:00-14:00'), ('Period 4', '14:00-16:00'), ('Period 5', '16:00-18:00'), ('Period 6', '18:00-20:00')], max_length=10),
        ),
    ]
