# Generated by Django 3.1.2 on 2021-01-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20210121_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.CharField(choices=[('8:00-10:00', 'Period 1'), ('10:00-12:00', 'Period 2'), ('12:00-14:00', 'Period 3'), ('14:00-16:00', 'Period 4'), ('16:00-18:00', 'Period 5'), ('18:00-20:00', 'Period 6')], max_length=18),
        ),
    ]
