# Generated by Django 3.1.2 on 2021-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20210123_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
