# Generated by Django 3.1.2 on 2021-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_auto_20210123_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
    ]
