# Generated by Django 3.1.2 on 2021-01-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_auto_20210123_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='courseselection',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseselection',
            name='username',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='username',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseGrade',
        ),
        migrations.DeleteModel(
            name='CourseSelection',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
