# Generated by Django 3.1.2 on 2021-01-23 18:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_auto_20210123_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('time', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10)),
                ('period', models.CharField(choices=[('Period 1', '8:00-10:00'), ('Period 2', '10:00-12:00'), ('Period 3', '12:00-14:00'), ('Period 4', '14:00-16:00'), ('Period 5', '16:00-18:00'), ('Period 6', '18:00-20:00')], max_length=18)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.student')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='edu.CourseSelection')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.student')),
            ],
        ),
    ]
