# Generated by Django 3.1.2 on 2021-01-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_course_coursegrade_courseselection_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_start',
        ),
    ]
