# Generated by Django 3.1.2 on 2021-01-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_auto_20210123_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_end',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
