# Generated by Django 3.1.2 on 2021-01-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_auto_20210123_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_end',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
