# Generated by Django 3.1.2 on 2021-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0015_auto_20210123_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_end',
            field=models.TimeField(null=True),
        ),
    ]
