# Generated by Django 3.1.2 on 2021-01-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0016_auto_20210123_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_end',
            field=models.TimeField(),
        ),
    ]
