# Generated by Django 3.1.2 on 2021-01-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_auto_20210123_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time_end',
        ),
        migrations.AddField(
            model_name='course',
            name='dura',
            field=models.DurationField(null=True),
        ),
    ]
