# Generated by Django 3.1.2 on 2021-01-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_auto_20210123_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dura',
            field=models.DurationField(),
        ),
    ]
