# Generated by Django 3.1.2 on 2021-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_auto_20210123_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='dura',
        ),
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
        migrations.AddField(
            model_name='course',
            name='time_end',
            field=models.TimeField(null=True),
        ),
    ]
