# Generated by Django 3.1.2 on 2021-01-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_auto_20210124_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_end',
            field=models.TimeField(),
        ),
    ]
