# Generated by Django 3.1.2 on 2021-01-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0023_auto_20210124_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_start',
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(choices=[('Period 1', '8:00-10:00'), ('Period 2', '10:00-12:00'), ('Period 3', '12:00-14:00'), ('Period 4', '14:00-16:00'), ('Period 5', '16:00-18:00'), ('Period 6', '18:00-20:00')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10, null=True),
        ),
    ]
