# Generated by Django 3.1.2 on 2021-01-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0026_auto_20210124_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='days',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='periods',
            new_name='period',
        ),
    ]
