# Generated by Django 3.1.6 on 2021-02-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0026_auto_20210208_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursegrade',
            old_name='grade',
            new_name='marks',
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('12', 'Grade 12'), ('11', 'Grade 11'), ('10', 'Grade 10'), ('9', 'Grade 9'), ('8', 'Grade 8'), ('7', 'Grade 7'), ('6', 'Grade 6'), ('5', 'Grade 5'), ('4', 'Grade 4'), ('3', 'Grade 3'), ('2', 'Grade 2'), ('1', 'Grade 1')], default='12', max_length=2),
        ),
    ]
