# Generated by Django 3.1.6 on 2021-02-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0027_auto_20210209_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseID',
        ),
        migrations.CreateModel(
            name='e_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
            ],
        ),
    ]
