# Generated by Django 3.1.2 on 2021-01-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0028_auto_20210124_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='periods',
            field=models.ManyToManyField(to='edu.Period'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(max_length=10),
        ),
    ]
