# Generated by Django 3.1.2 on 2021-01-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0029_auto_20210124_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.RemoveField(
            model_name='day',
            name='periods',
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.day')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.period')),
            ],
        ),
    ]
