# Generated by Django 3.1.5 on 2021-02-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0030_auto_20210124_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.teacher'),
        ),
    ]
