# Generated by Django 3.1.5 on 2021-02-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0032_auto_20210202_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeTable',
            new_name='Classes',
        ),
    ]
