# Generated by Django 3.1.5 on 2021-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0034_course_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='course',
            new_name='courseID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.AddField(
            model_name='classes',
            name='section',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
